---
- name: Ensure gickup config folder exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ gickup_host_path }}"
    - "{{ gickup_host_path }}/log"

- name: Copy gickup docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ gickup_host_path }}/docker-compose.yml"
    mode: 0644
  become: true

- name: Create systemd gickup service.
  ansible.builtin.template:
    src: templates/gickup.service.j2
    dest: "/etc/systemd/system/gickup.service"
    mode: 0644
  become: true

- name: Ensure gickup.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: gickup
  become: true

- name: Remove old image versions
  become: true
  docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
