---
- name: Prepare
  hosts: all
  become: true
  vars:
    docker_compose_version: "v2.4.1"
    gickup_host_path: /etc/gickup
    gickup_host_backup_path: /tmp/backup
    gickup_config_content: |
      source:
      cron: 5 4 * * 5 # At 04:05 on Friday.
    pip_install_packages:
      - requests
      - docker
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
